name: backend_websocket
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^2.14.0
  postgres: ^3.2.1
  postgresql2: ^1.6.2
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
# path: ^1.8.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
